resolver: lts-12.20
packages:
- .
extra-deps:
- reflex-0.6.3
- reflex-dom-0.5.3
- reflex-dom-core-0.5.3
- ghcjs-dom-0.9.4.0
- ghcjs-dom-jsaddle-0.9.4.0
- jsaddle-0.9.7.0
- jsaddle-dom-0.9.4.0
- bimap-0.3.3
- dependent-map-0.3
- dependent-sum-0.6.2.0
- dependent-sum-template-0.1.0.0
- constraints-extras-0.3.0.2
- ref-tf-0.4.0.2
- monoidal-containers-0.6.0.1
- witherable-0.3.1
- zenc-0.1.1